/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "/home/hpe/NTUST-script/CONFIG/F1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-APER -no-gen-BER -no-gen-JER -no-gen-OER -gen-UPER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/hpe/o-du-l2/src/codec_utils/F1AP`
 */

#ifndef	_DCBasedDuplicationConfigured_H_
#define	_DCBasedDuplicationConfigured_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DCBasedDuplicationConfigured {
	DCBasedDuplicationConfigured_true	= 0,
	/*
	 * Enumeration is extensible
	 */
	DCBasedDuplicationConfigured_false	= 1
} e_DCBasedDuplicationConfigured;

/* DCBasedDuplicationConfigured */
typedef long	 DCBasedDuplicationConfigured_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DCBasedDuplicationConfigured_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DCBasedDuplicationConfigured;
extern const asn_INTEGER_specifics_t asn_SPC_DCBasedDuplicationConfigured_specs_1;
asn_struct_free_f DCBasedDuplicationConfigured_free;
asn_struct_print_f DCBasedDuplicationConfigured_print;
asn_constr_check_f DCBasedDuplicationConfigured_constraint;
xer_type_decoder_f DCBasedDuplicationConfigured_decode_xer;
xer_type_encoder_f DCBasedDuplicationConfigured_encode_xer;
per_type_decoder_f DCBasedDuplicationConfigured_decode_uper;
per_type_encoder_f DCBasedDuplicationConfigured_encode_uper;
per_type_decoder_f DCBasedDuplicationConfigured_decode_aper;
per_type_encoder_f DCBasedDuplicationConfigured_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DCBasedDuplicationConfigured_H_ */
#include <asn_internal.h>
