/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "/home/hpe/NTUST-script/CONFIG/F1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-APER -no-gen-BER -no-gen-JER -no-gen-OER -gen-UPER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/hpe/o-du-l2/src/codec_utils/F1AP`
 */

#ifndef	_DRXConfigurationIndicator_H_
#define	_DRXConfigurationIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DRXConfigurationIndicator {
	DRXConfigurationIndicator_release	= 0
	/*
	 * Enumeration is extensible
	 */
} e_DRXConfigurationIndicator;

/* DRXConfigurationIndicator */
typedef long	 DRXConfigurationIndicator_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DRXConfigurationIndicator_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DRXConfigurationIndicator;
extern const asn_INTEGER_specifics_t asn_SPC_DRXConfigurationIndicator_specs_1;
asn_struct_free_f DRXConfigurationIndicator_free;
asn_struct_print_f DRXConfigurationIndicator_print;
asn_constr_check_f DRXConfigurationIndicator_constraint;
xer_type_decoder_f DRXConfigurationIndicator_decode_xer;
xer_type_encoder_f DRXConfigurationIndicator_encode_xer;
per_type_decoder_f DRXConfigurationIndicator_decode_uper;
per_type_encoder_f DRXConfigurationIndicator_encode_uper;
per_type_decoder_f DRXConfigurationIndicator_decode_aper;
per_type_encoder_f DRXConfigurationIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DRXConfigurationIndicator_H_ */
#include <asn_internal.h>
