/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "/home/hpe/NTUST-script/CONFIG/F1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-APER -no-gen-BER -no-gen-JER -no-gen-OER -gen-UPER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/hpe/o-du-l2/src/codec_utils/F1AP`
 */

#ifndef	_EUTRA_NR_CellResourceCoordinationReq_Container_H_
#define	_EUTRA_NR_CellResourceCoordinationReq_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EUTRA-NR-CellResourceCoordinationReq-Container */
typedef OCTET_STRING_t	 EUTRA_NR_CellResourceCoordinationReq_Container_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUTRA_NR_CellResourceCoordinationReq_Container;
asn_struct_free_f EUTRA_NR_CellResourceCoordinationReq_Container_free;
asn_struct_print_f EUTRA_NR_CellResourceCoordinationReq_Container_print;
asn_constr_check_f EUTRA_NR_CellResourceCoordinationReq_Container_constraint;
xer_type_decoder_f EUTRA_NR_CellResourceCoordinationReq_Container_decode_xer;
xer_type_encoder_f EUTRA_NR_CellResourceCoordinationReq_Container_encode_xer;
per_type_decoder_f EUTRA_NR_CellResourceCoordinationReq_Container_decode_uper;
per_type_encoder_f EUTRA_NR_CellResourceCoordinationReq_Container_encode_uper;
per_type_decoder_f EUTRA_NR_CellResourceCoordinationReq_Container_decode_aper;
per_type_encoder_f EUTRA_NR_CellResourceCoordinationReq_Container_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EUTRA_NR_CellResourceCoordinationReq_Container_H_ */
#include <asn_internal.h>
