/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "/home/hpe/NTUST-script/CONFIG/F1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-APER -no-gen-BER -no-gen-JER -no-gen-OER -gen-UPER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/hpe/o-du-l2/src/codec_utils/F1AP`
 */

#ifndef	_MeasGapConfig_H_
#define	_MeasGapConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasGapConfig */
typedef OCTET_STRING_t	 MeasGapConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasGapConfig;
asn_struct_free_f MeasGapConfig_free;
asn_struct_print_f MeasGapConfig_print;
asn_constr_check_f MeasGapConfig_constraint;
xer_type_decoder_f MeasGapConfig_decode_xer;
xer_type_encoder_f MeasGapConfig_encode_xer;
per_type_decoder_f MeasGapConfig_decode_uper;
per_type_encoder_f MeasGapConfig_encode_uper;
per_type_decoder_f MeasGapConfig_decode_aper;
per_type_encoder_f MeasGapConfig_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasGapConfig_H_ */
#include <asn_internal.h>
