/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "/home/hpe/NTUST-script/CONFIG/F1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-APER -no-gen-BER -no-gen-JER -no-gen-OER -gen-UPER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/hpe/o-du-l2/src/codec_utils/F1AP`
 */

#ifndef	_NGRANAllocationAndRetentionPriority_H_
#define	_NGRANAllocationAndRetentionPriority_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PriorityLevel.h"
#include "Pre-emptionCapability.h"
#include "Pre-emptionVulnerability.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* NGRANAllocationAndRetentionPriority */
typedef struct NGRANAllocationAndRetentionPriority {
	PriorityLevel_t	 priorityLevel;
	Pre_emptionCapability_t	 pre_emptionCapability;
	Pre_emptionVulnerability_t	 pre_emptionVulnerability;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGRANAllocationAndRetentionPriority_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGRANAllocationAndRetentionPriority;
extern asn_SEQUENCE_specifics_t asn_SPC_NGRANAllocationAndRetentionPriority_specs_1;
extern asn_TYPE_member_t asn_MBR_NGRANAllocationAndRetentionPriority_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NGRANAllocationAndRetentionPriority_H_ */
#include <asn_internal.h>
