/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-CommonDataTypes"
 * 	found in "/home/hpe/NTUST-script/CONFIG/F1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-APER -no-gen-BER -no-gen-JER -no-gen-OER -gen-UPER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/hpe/o-du-l2/src/codec_utils/F1AP`
 */

#ifndef	_ProtocolExtensionID_H_
#define	_ProtocolExtensionID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolExtensionID */
typedef long	 ProtocolExtensionID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionID;
asn_struct_free_f ProtocolExtensionID_free;
asn_struct_print_f ProtocolExtensionID_print;
asn_constr_check_f ProtocolExtensionID_constraint;
xer_type_decoder_f ProtocolExtensionID_decode_xer;
xer_type_encoder_f ProtocolExtensionID_encode_xer;
per_type_decoder_f ProtocolExtensionID_decode_uper;
per_type_encoder_f ProtocolExtensionID_encode_uper;
per_type_decoder_f ProtocolExtensionID_decode_aper;
per_type_encoder_f ProtocolExtensionID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolExtensionID_H_ */
#include <asn_internal.h>
