/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "F1AP-IEs"
 * 	found in "/home/hpe/NTUST-script/CONFIG/F1.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-APER -no-gen-BER -no-gen-JER -no-gen-OER -gen-UPER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/hpe/o-du-l2/src/codec_utils/F1AP`
 */

#ifndef	_PWSSystemInformation_H_
#define	_PWSSystemInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SIBType-PWS.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* PWSSystemInformation */
typedef struct PWSSystemInformation {
	SIBType_PWS_t	 sIBtype;
	OCTET_STRING_t	 sIBmessage;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PWSSystemInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PWSSystemInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_PWSSystemInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_PWSSystemInformation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PWSSystemInformation_H_ */
#include <asn_internal.h>
