/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "/home/hpe/NTUST-script/CONFIG/E2APV0300.asn1"
 * 	`asn1c -gen-APER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/hpe/o-du-l2/src/codec_utils/E2AP`
 */

#ifndef	_ProtocolIE_ContainerPair_H_
#define	_ProtocolIE_ContainerPair_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_ContainerPair_H_ */
#include <asn_internal.h>
