/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "/home/hpe/NTUST-script/CONFIG/E2APV0300.asn1"
 * 	`asn1c -gen-APER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D /home/hpe/o-du-l2/src/codec_utils/E2AP`
 */

#ifndef	_RICsubscription_withCauseE2_Item_H_
#define	_RICsubscription_withCauseE2_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RICrequestID.h"
#include "RANfunctionID.h"
#include "CauseE2.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RICsubscription-withCauseE2-Item */
typedef struct RICsubscription_withCauseE2_Item {
	RICrequestID_t	 ricRequestID;
	RANfunctionID_t	 ranFunctionID;
	CauseE2_t	 cause;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICsubscription_withCauseE2_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICsubscription_withCauseE2_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RICsubscription_withCauseE2_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RICsubscription_withCauseE2_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RICsubscription_withCauseE2_Item_H_ */
#include <asn_internal.h>
